### ISSUE TITLE
updating 3.0.1 to 3.0.2 fails. Ketchup 3.à.2 on 3.0.2 fails

### ISSUE THREAD

**Issue by EricV** [psomas/ketchup#1]
Title says all. I tried the debian version then retried with git (linux3 branch).

**Comment by psomas** [comment]
I pushed a change to fix an issue with get_ver() function and 3.x kernels (which could cause some problems), but kernel.org has some mirroring problems right now too, and it's likely that it's due to that (for example, without the --no-gpg flag, ketchup will try to find the .bz2.sign signature, which is not yet available for 3.0.2 at kernel.org and will fail -- although we should probably fix that too). Is this the error you're getting?

Btw, kernel.org keep changing the URLs (for the -rc releases for example), and it's likely that 3.0-rcs will work, while 3.1-rcs won't, or vice versa.

**Comment by EricV** [comment]
On 16/08/2011 21:54, psomas wrote:

> I pushed a change to fix an issue with get_ver() function and 3.x kernels (which could cause some problems), but kernel.org has some mirroring problems right now too, and it's likely that it's due to that (for example, without the --no-gpg flag, ketchup will try to find the .bz2.sign signature, which is not yet available for 3.0.2 at kernel.org and will fail -- although we should probably fix that too). Is this the error you're getting?
> 
> Btw, kernel.org keep changing the URLs (for the -rc releases for example), and it's likely that 3.0-rcs will work, while 3.1-rcs won't, or vice versa.

I correctly update from 2.6.39.3 to 3.0.1 yesterday. Today I tried to 
upgrade to 3.0.2 from 3.0.1 and it tries to apply 3.0.2 without first 
removing 3.0.1.

I did it manually and then tried to do what should be a nop operation 
3.0.2 to 3.0.2 and it tries to apply 3.0.2 anyway.

-- eric

**Comment by EricV** [comment]
Tested your last hour fix and yes it fixes the problem.
